#!/usr/bin/env python3
"""Generate compact Agent views from leader-generated JState Markdown."""

from __future__ import annotations

import re
from pathlib import Path

from normalize_bc_agent_docs import repair


ROOT = Path(__file__).resolve().parent
SOURCE_DIR = ROOT / "nav-navigation-errors"
OUTPUT_DIR = ROOT / "agent"
SECTION_RE = re.compile(r"(?m)^##\s+(\d+)\s+[^\n]+$")
ERROR_DOC_RE = re.compile(r"^\d{6}-.*\.md$")


def split_sections(content: str) -> tuple[str, dict[int, str]]:
    matches = list(SECTION_RE.finditer(content))
    if not matches:
        return content.rstrip(), {}
    preamble = content[: matches[0].start()].rstrip()
    sections: dict[int, str] = {}
    for index, match in enumerate(matches):
        end = matches[index + 1].start() if index + 1 < len(matches) else len(content)
        sections[int(match.group(1))] = content[match.start() : end].rstrip()
    return preamble, sections


def build_agent_view(source: Path) -> tuple[str, bool, list[str]]:
    content = source.read_text(encoding="utf-8-sig")
    preamble, sections = split_sections(content)
    warnings: list[str] = []
    selected = [number for number in (1, 3, 5, 6) if number in sections]

    if 6 not in sections and 4 in sections:
        selected.append(4)
        warnings.append("missing_playbook: section 4 included as fallback")
    selected.sort()

    for required in (1, 3, 5):
        if required not in sections:
            warnings.append(f"missing_section_{required}")

    body = (
        "\n\n".join(sections[number] for number in selected)
        if selected
        else content.rstrip()
    )
    header = (
        "<!-- AUTO-GENERATED by generate_agent_docs.py; do not edit directly. -->\n"
        f"<!-- Source: nav-navigation-errors/{source.name} -->\n\n"
    )
    source_note = (
        "\n\n> Agent 视图：仅保留结论、诊断决策、证据/输出契约和 Playbook。"
        f"完整原文见 [{source.name}](../nav-navigation-errors/{source.name})。"
    )
    return f"{header}{preamble}{source_note}\n\n{body}\n", 6 in sections, warnings


def main() -> int:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    sources = sorted(path for path in SOURCE_DIR.glob("*.md") if ERROR_DOC_RE.match(path.name))
    playbook_count = 0
    warning_count = 0

    for source in sources:
        output, has_playbook, warnings = build_agent_view(source)
        (OUTPUT_DIR / source.name).write_text(output, encoding="utf-8", newline="\n")
        playbook_count += int(has_playbook)
        if warnings:
            warning_count += 1
            print(f"warning {source.name}: {', '.join(warnings)}")

    repaired_count = sum(repair(OUTPUT_DIR / source.name) for source in sources)
    print(f"source_count={len(sources)}")
    print(f"playbook_count={playbook_count}")
    print(f"missing_playbook_count={len(sources) - playbook_count}")
    print(f"warning_document_count={warning_count}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
